name: Employee-Frontend-DevSecOps-Workflow

on:
  push:
    branches: [ development ]
  workflow_dispatch:

jobs:
  # sonarcloud-scan-job:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Setup Node.js 18
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '18'

  #     - name: Install dependencies
  #       run: npm install

  #     - name: SonarCloud Scan
  #       uses: sonarsource/sonarcloud-github-action@master
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #       with:
  #         args: >
  #           -Dsonar.organization=nishanthkumarpathi
  #           -Dsonar.projectKey=nishanthkumarpathi_employee-frontend
  #           -Dsonar.sources=.
  #           -Dsonar.host.url=https://sonarcloud.io

  # synk-scan-job:
  #   runs-on: ubuntu-latest
  #   # needs: sonarcloud-scan-job
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Setup Node.js 18
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '18'

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Run Snyk to check for vulnerabilities
  #       uses: snyk/actions/node@master
  #       continue-on-error: true
  #       env:
  #         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  #       with:
  #         args: --sarif-file-output=snyk.sarif
  #         command: test

  component-analysis:
    name: ComponentAnalysis-Node-NPMAudit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install the Libraries or Node Modules
        run: npm install

      - name: Perform Node.js Audit and Output to Json file
        run: npm audit --json >> node-audit-results.json
        continue-on-error: true

      - name: List the files available
        run: ls
      
      - name: Upload the Output as an artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: NodeAudit Output
          path: node-audit-results.json
        if: always()

  oast-frontend-retirejs:
    name: SAST-Frontend-Job-NodeJS-RetireJS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install the Libraries or Node Modules
        run: npm install

      - name: Perform RetireJS Scan
        run: npx retire --outputformat json >> retirejs-results.json
        continue-on-error: true

      - name: List the files available
        run: ls

      - name: Upload the Output as an artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: RetireJS Output
          path: retirejs-results.json
        if: always()