name: Employee-Frontend-DevSecOps-Workflow

on:
  push:
    branches: [ development ]

jobs:
  sonarscanjob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=nishanthkumarpathi
            -Dsonar.projectKey=nishanthkumarpathi_employee-frontend
            -Dsonar.sources=.
            -Dsonar.host.url=https://sonarcloud.io